# SPDX-License-Identifier: GPL-3.0-or-later
# HWC1 exposes VNDK 31 but no observed board API property.
TARGET_BOARD_API_LEVEL="none"
TARGET_LEGACY_VNDK_VERSION=31
TARGET_PRODUCT_SHIPPING_API_LEVEL=28
TARGET_USE_DYNAMIC_PARTITIONS=false
TARGET_OS_SINGLE_SYSTEM_IMAGE="essi"
TARGET_OS_BUILD_SYSTEM_EXT_PARTITION=false
TARGET_DISABLE_AVB_SIGNING=true
TARGET_KEEP_ORIGINAL_SIGN=true
